### ISSUE TITLE
Secret Management: SIGSEGV fault when using secret manager in dataproc

### ISSUE THREAD

**Issue by vchekan** [googleapis/java-secretmanager#692]
#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: Linux, Debian-10, google's dataproc image: 1.5-debian10
3. Java version: 8.0_312-b07
4. google-cloud-java version(s): com.google.cloud:libraries-bom:24.2.0, com.google.cloud:google-cloud-secretmanager:2.0.7

#### Steps to reproduce

  1. Compile project and generate uber-jar: `./gradlew shadowJar`
  2. Copy jar to gcp: gsutil cp ./build/libs/gcp-secret-error-0.1-uber.jar $BUCKET
  3. Create cluster (see script below)
  4. Ssh into master node and run `spark-submit --class=com.test.Main $BUCKET/gcp-secret-error-0.1-uber.jar`
  5. Observe:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f96ba0b4c80, pid=11573, tid=0x00007f97116fb700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00007f96ba0b4c80
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/.../hs_err_pid11573.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
Aborted
```

#### Code example

Create cluster.
```bash
   gcloud dataproc clusters create $CLUSTER --enable-component-gateway \
   --region $REGION --no-address --bucket $BUCKET --zone $ZONE --max-idle 1800s \
   --master-machine-type n1-standard-4 --master-boot-disk-size 500 --num-workers 1 --worker-machine-type n1-standard-4 --worker-boot-disk-size 1000 --image-version 1.5-debian10 \
   --scopes 'https://www.googleapis.com/auth/cloud-platform' --project $PROJECT \
   --subnet $SUBNET
```

build.gradle.kts
```kotlin
plugins {
    java
    scala
    id("com.github.johnrengelman.shadow")
}

tasks.shadowJar {
    archiveClassifier.set("uber")
    isZip64 = true
    append("reference.conf")

    relocate("com.google.common", "shade.com.google.common")
    relocate("com.google.protobuf", "shade.com.google.protobuf")
}

version = "0.1"

dependencies {
    implementation("org.scala-lang:scala-library:2.12.14")
    compileOnly("org.apache.spark:spark-core_2.12:2.4.8")
    implementation(platform("com.google.cloud:libraries-bom:24.2.0"))
    implementation("com.google.cloud:google-cloud-secretmanager")
}


tasks.jar { manifest { attributes.set("Main-Class", "com.test.Main") } }
```

settings.gradle.kts
```kotlin
rootProject.name = "gcp-secret-error"

pluginManagement {
    plugins {
        id("com.github.johnrengelman.shadow") version "7.0.0"
    }
}
```

src/main/scala/com/test/Main.scala
```scala
package com.test

import com.google.cloud.secretmanager.v1.{SecretManagerServiceClient, SecretVersionName}

object Main {
  def main(args: Array[String]) {

    val client = SecretManagerServiceClient.create()
    val version = SecretVersionName.of("test.project", "test.name", "latest")
    val response = client.accessSecretVersion(version)
    response.getPayload.getData.toStringUtf8
    client.close()

    println("ok")
  }
}
```

#### Native frames from hs_err_pid11573.log
```
Stack: [0x00007f97115fc000,0x00007f97116fc000],  sp=0x00007f97116f8cf8,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007f96ba0b4c80
j  io.grpc.netty.shaded.io.netty.internal.tcnative.Library.initialize(Ljava/lang/String;Ljava/lang/String;)Z+31
j  io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.initializeTcNative(Ljava/lang/String;)Z+4
j  io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>()V+240
v  ~StubRoutines::call_stub
V  [libjvm.so+0x694f8a]
V  [libjvm.so+0x64f8d2]
V  [libjvm.so+0x64fdb0]
V  [libjvm.so+0x650221]
V  [libjvm.so+0x8188c0]
V  [libjvm.so+0x81d15e]
V  [libjvm.so+0x81feb0]
V  [libjvm.so+0x686ff3]
j  io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider()Lio/grpc/netty/shaded/io/netty/handler/ssl/SslProvider;+0
j  io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(Lio/grpc/netty/shaded/io/netty/handler/ssl/SslContextBuilder;)Lio/grpc/netty/shaded/io/netty/handler/ssl/SslContextBuilder;+1
j  io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient()Lio/grpc/netty/shaded/io/netty/handler/ssl/SslContextBuilder;+3
j  io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator()Lio/grpc/netty/shaded/io/grpc/netty/ProtocolNegotiator;+19
j  io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory()Lio/grpc/internal/ClientTransportFactory;+8
j  io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory()Lio/grpc/internal/ClientTransportFactory;+4
j  io.grpc.internal.ManagedChannelImplBuilder.build()Lio/grpc/ManagedChannel;+13
j  io.grpc.internal.AbstractManagedChannelImplBuilder.build()Lio/grpc/ManagedChannel;+4
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel()Lio/grpc/ManagedChannel;+472
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1900(Lcom/google/api/gax/grpc/InstantiatingGrpcChannelProvider;)Lio/grpc/ManagedChannel;+1
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel()Lio/grpc/ManagedChannel;+4
j  com.google.api.gax.grpc.ChannelPool.create(ILcom/google/api/gax/grpc/ChannelFactory;)Lcom/google/api/gax/grpc/ChannelPool;+17
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel()Lcom/google/api/gax/rpc/TransportChannel;+45
j  com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel()Lcom/google/api/gax/rpc/TransportChannel;+37
j  com.google.api.gax.rpc.ClientContext.create(Lcom/google/api/gax/rpc/StubSettings;)Lcom/google/api/gax/rpc/ClientContext;+179
j  com.google.cloud.secretmanager.v1.stub.GrpcSecretManagerServiceStub.create(Lcom/google/cloud/secretmanager/v1/stub/SecretManagerServiceStubSettings;)Lcom/google/cloud/secretmanager/v1/stub/GrpcSecretManagerServiceStub;+6
j  com.google.cloud.secretmanager.v1.stub.SecretManagerServiceStubSettings.createStub()Lcom/google/cloud/secretmanager/v1/stub/SecretManagerServiceStub;+19
j  com.google.cloud.secretmanager.v1.SecretManagerServiceClient.<init>(Lcom/google/cloud/secretmanager/v1/SecretManagerServiceSettings;)V+17
j  com.google.cloud.secretmanager.v1.SecretManagerServiceClient.create(Lcom/google/cloud/secretmanager/v1/SecretManagerServiceSettings;)Lcom/google/cloud/secretmanager/v1/SecretManagerServiceClient;+5
j  com.google.cloud.secretmanager.v1.SecretManagerServiceClient.create()Lcom/google/cloud/secretmanager/v1/SecretManagerServiceClient;+6
j  com.test.Main$.main([Ljava/lang/String;)V+0
j  com.test.Main.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub
V  [libjvm.so+0x694f8a]
V  [libjvm.so+0x9eb4b8]
V  [libjvm.so+0x9ece86]
V  [libjvm.so+0x740255]  JVM_InvokeMethod+0x115
j  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100
j  sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+56
j  org.apache.spark.deploy.JavaMainApplication.start([Ljava/lang/String;Lorg/apache/spark/SparkConf;)V+97
j  org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(Lorg/apache/spark/deploy/SparkSubmitArguments;Z)V+507
j  org.apache.spark.deploy.SparkSubmit.doRunMain$1(Lorg/apache/spark/deploy/SparkSubmitArguments;Z)V+111
j  org.apache.spark.deploy.SparkSubmit.submit(Lorg/apache/spark/deploy/SparkSubmitArguments;Z)V+65
j  org.apache.spark.deploy.SparkSubmit.doSubmit([Ljava/lang/String;)V+78
j  org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit([Ljava/lang/String;)V+2
j  org.apache.spark.deploy.SparkSubmit$.main([Ljava/lang/String;)V+10
j  org.apache.spark.deploy.SparkSubmit.main([Ljava/lang/String;)V+4
v  ~StubRoutines::call_stub
V  [libjvm.so+0x694f8a]
V  [libjvm.so+0x715af7]
V  [libjvm.so+0x7182a1]
C  [libjli.so+0x8890]
C  [libpthread.so.0+0x7fa3]  start_thread+0xf3
```

#### External references such as API reference guides used	

- https://cloud.google.com/dataproc/docs/guides/manage-spark-dependencies

#### Any additional information below	
I suspect that this issue might be relevant: https://github.com/netty/netty/issues/11879 and this crash is result of 2 different versions of netty packaged into dataproc/spark and secretmanager/grpc.

There is also similar sounding issue: https://github.com/googleapis/google-cloud-java/issues/1522

Notice, that only google-provided resources are used: unmodified google's dataproc image `1.5-debian10` and google's `com.google.cloud:google-cloud-secretmanager` and this combination leads to SIGSEGV.

**Comment by lesv** [comment]
Hi @vchekan - this is a fairly common issue.  I just wrote about this in an email which I'll post first incase it helps, then I'll try reading through this again and see if I can add something more.

>There isn't anything inherently wrong w/ SecretManager.  In fact, it's fairly simple as client libraries go.  If it's broken, you've probably got something weird going on.  When integrating with large complex Java things, it's super important they use the [Libraries-BOM](https://cloud.google.com/java/docs/bom).   Most of these large projects use a custom java class loader that helps prevent conflicts with user code, but it's not the only place these things arise.

>Lots of these large projects use older versions of Guava, ProtoBuf, and Netty which is usually ok when we don't link with their API libraries.  Using the BOM fixes most problems, but not all.  The problem is known as the [Diamond Dependency Conflict](https://jlbp.dev/what-is-a-diamond-dependency-conflict).

>It's very important that they use the minimum required classes so bad things don't get accidentally pulled in.  (Again, the BOM usually helps with this).

>They should also be told about how to debug what often seem like weird unexpected results.
We start with:   `mvn dependency:tree` and look for duplicate artifacts with differing versions. (esp substantially different major versions)  (or the [Gradle](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html) equivalent).

**Comment by lesv** [comment]
@vchekan You might wish to be clear which version of Dataproc you want when you create the cluster.  
[Overview](https://cloud.google.com/dataproc/docs/concepts/versioning/overview) [2.0](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.0) [1.5](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.5) [1.4](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.4) [Images](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions)

**Comment by lesv** [comment]
@vchekan 
* I saw a similar bug that got fixed by upgrading to Dataproc 2.0.  
* Netty is shaded by gRPC
* Does your code use / need spark-core?  As compile only it shouldn't be a conflict, but if it's not needed you might wish to get rid of it.
* You might wish to update to 24.3.0 of the BOM
* Thanks for mentioning the [manage spark dependencies](https://cloud.google.com/dataproc/docs/guides/manage-spark-dependencies) page. 
  *  It mentions that Hadoop 3.0 fixed some problems around dependency management.  Another reason to upgrade to Dataproc 2.x
  * [The Scala plugin](https://docs.gradle.org/current/userguide/scala_plugin.html) mentioned for those following along.
  * Unless it's from Scala, I'm not sure what's included that requires shading for spark.  I haven't looked at the source code, but as I mentioned in my note earlier, most large java things have smart class loaders.  It's possible they are providing their API so you don't need to, which would make sense as you are `compileOnly` for spark - which might explain why they recommend shading Guava & protobuf.

If you could try moving to Dataproc 2.x instead of 1.5 and trying things, I suspect things will improve.

I'm doing this all from memory and reading and won't get a chance to try it on a real system until Friday at the earliest. (and Monday is a holiday for us).

**Comment by lesv** [comment]
I'm going to close this since there are some known issues and remediation steps.  Feel free to reopen if you require addtional assistance.

**Comment by vchekan** [comment]
@lesv thanks for your reply. I will try to upgrade to dataproc-2..0

**Comment by ovGoogle** [comment]
I used those same versions for libraries-bom and google-cloud-secretmanager on spark-shell, using the standard image for Dataproc 2.0. I got the exact same error. 

I upgraded the libraries to 24.3.0 and 2.1.2 (the latest), and the error changes to:

> Exception in thread "grpc-default-executor-0" java.lang.IllegalAccessError: tried to access field com.google.protobuf.AbstractMessage.memoizedSize from class com.google.cloud.secretmanager.v1.AccessSecretVersionRequest
>         at com.google.cloud.secretmanager.v1.AccessSecretVersionRequest.getSerializedSize(AccessSecretVersionRequest.java:195)
>         at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)
>         at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)
>         at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)
>         at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
>         at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
>         at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
>         at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
>         at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
>         at io.grpc.internal.MetadataApplierImpl.finalizeWith(MetadataApplierImpl.java:110)
>         at io.grpc.internal.MetadataApplierImpl.apply(MetadataApplierImpl.java:78)
>         at io.grpc.auth.GoogleAuthLibraryCallCredentials$1.onSuccess(GoogleAuthLibraryCallCredentials.java:131)
>         at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:549)
>         at com.google.auth.oauth2.OAuth2Credentials$FutureCallbackToMetadataCallbackAdapter.onSuccess(OAuth2Credentials.java:540)
>         at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1078)
>         at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
>         at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:141)
>         at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:130)
>         at com.google.common.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:86)
>         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
>         at java.util.concurrent.FutureTask.set(FutureTask.java:233)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:274)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:750)


Which seems to be yet another diamond dependency conflict (with Protobuf this time). We still can't use the secretmanager libraries for Java.

**Comment by suztomo** [comment]
The environment is providing an old version of Protobuf. Please ensure you use a newer version of Protobuf. For example, the [Libraries BOM 25.4.0](https://github.com/googleapis/java-cloud-bom/releases/tag/libraries-bom-v25.4.0) has Protobuf Java: 3.20.1.

The `memoizedSize` field is protected field https://github.com/protocolbuffers/protobuf/blob/520c601c99012101c816b6ccc89e8d6fc28fdbb8/java/core/src/main/java/com/google/protobuf/AbstractMessage.java#L119.


AccessSecretVersionRequest extends GeneratedMessageV3, which extends AbstractMessage. It can access `memoizedSize`.

```
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
```
